### ISSUE TITLE
Prevent opening powershell if build fails

### ISSUE THREAD

**Issue by SailReal** [SharkCagey/HTWG_shark_cage#28]

**Comment by DonatJR** [comment]
Stopping build after one project fails is not as easy as it sounds: projects are by default built in parallel and VS does not support parallel builds and aborting on first build failure in conjunction. I'm experimenting with making the powershell script the startup project for the solution and then only trigger it on `Run` instead of on `Build`

**Comment by DonatJR** [comment]
done with #37
