### ISSUE TITLE
Enhance build process 

### ISSUE THREAD

**Issue by SailReal** [SharkCagey/HTWG_shark_cage#6]
* Stop and restart service automatically after (debug) build
* Make deploy folder configurable

**Comment by DonatJR** [comment]
@SailReal  @DaeVo  @baWedekind 
I changed the build process to execute a powershell script on (re)build which asks the user where to copy the binaries and then (re)installs the service, but it is based on (the as of yet unreviewed) PR #20 which is why I can't create a PR for it yet. If you want to take a look I created a branch: https://github.com/SharkCagey/HTWG_shark_cage/tree/6-enhance-build-process
